### ISSUE TITLE
Desktop client does not sync changes made via web UI - when user folder was prepopulated

### ISSUE THREAD

**Issue by jnweiger** [owncloud/product#127]
Reproduce on ocis 1.0.0-beta8 with eos installed via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

On a second hetzner cloud machine start an ubuntu desktop and install desktop client
Version 2.7.0 (build 1868) dated Jul 23 2020, 01:48:16

* connect client to server, wait for initial sync
* also log in with firefox to the same account.
* upload a file through the client. refresh the web ui, the file can be seen.
* upload a file through firefox. Wait. nothing happes.
* force sync in the client. Nothing happens. 
* log out the client account. log in. Nothing happens.
* remove the client sync connection. re-connect. Now it downloads.

Expected behaviour: 

* server and client stay in sync

**Comment by michaelstingl** [comment]
> * upload a file through the client. refresh the web ui, the file can be seen.
> * upload a file through firefox. Wait. nothing happes.

Name of the file? What to look for?

> * Create a 'New Folder' in multiple places in the Web UI.
> * (optional: add files inside the 'New Folder' via web UI)

Nothing about 'New Folder' in the provided log

@micbar do we have a test setup?

**Comment by michaelstingl** [comment]
I extracted all the `PROPFIND` for `/remote.php/dav/files/admin/` (polling for changes), and the etag didn't change that much…

```
% grep getetag PROPFIND-client-2.7.0-1868-daily-vs-ocis-1.0.0-beta8-202007231851.log
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19500445338&quot;</d:getetag>
<d:getetag>&quot;5f1950045e433&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;94abb7ef316fa44fe95479119b4ad008&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
<d:getetag>&quot;5f19bb76bf8e5&quot;</d:getetag>
```

[PROPFIND-client-2.7.0-1868-daily-vs-ocis-1.0.0-beta8-202007231851.log.zip](https://github.com/owncloud/product/files/4989886/PROPFIND-client-2.7.0-1868-daily-vs-ocis-1.0.0-beta8-202007231851.log.zip)

**Comment by PVince81** [comment]
as far as I heard, EOS is supposed to do etag propagation on its own, so shouldn't need any code in Reva to do so.
strange that it's not doing it, maybe still needs a little push of some sorts

**Comment by swoichha** [comment]
I wrote api tests for changes in e-tag(see https://github.com/owncloud/core/pull/37795) and it failed randomly in `ocis-reva`, reason being that the e-tag didn't change. While running these tests locally I found out that the `e-tag` for a file and it's parent folder is same.

What I did was I checked e-tag of `root` which was `5fae1bc72c889a5be84cc4713bee9cb6` at the beginning and then I create a folder called `upload` and I checked the e-tag again. For `root` it was `f291cc053ebe033855ec8a6ff1f02914` and for `upload`  it was `f291cc053ebe033855ec8a6ff1f02914`. No difference in e-tag which I think should not have happened. Then I uploaded a file `file.txt` with content "uploaded content". After that when I checked the e-tag it was similar for both folder `upload` and file `file.txt` which was `e655bb5c5c4b644bbf3b1693a05520eb`. Whereas the e-tag for root was changed into `967732929b0a614be458a96b1266fdde`.

**Comment by jnweiger** [comment]
## retested with
 * ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
 * and desktop daily (20200915) client ownCloud version 2.7.0 (build 2106) on Ubuntu 20.04

connect client. wait unitl initial sync completes.
Place file 5.5GB.mp3 in the client sync folder. It uploads. OK.
On the server execute `eos -r 0 0 rm -F '/eos/dockertest/reva/users/4/4c510ada-c86b-4815-8820-42cdf82c3d51/5.5GB.mp3'
Wait. Nothing happens.
Force sync now on the client: nothing happens.

The desktop client should discover the server side delete, and also delete locally.

**Comment by jnweiger** [comment]
## retested with
 * ocis-master via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
 * and desktop daily (20200915) client ownCloud version 2.7.0 (build 2106) on Ubuntu 20.04

<details>
<summary>Version details ocis-master</summary>

<pre>

```
OCIS_VERSION:         master
ocis --version:       ocis version 3f8fb10
git log:              commit 3f8fb10990c37377a0e102492922ffd4807571d6 (HEAD -> refs/heads/master, refs/remotes/origin/master, refs/remotes/origin/HEAD)
eos --version:        EOS 4.6.5 (2019)
xrootd -v:            v4.11.0
bin/ocis contains:
        owncloud/ocis-accounts@v0.4.2-0.20200911161616-e55b8ae2f440
        owncloud/ocis-glauth@v0.5.1-0.20200909064150-0735ec933777
        owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
        owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
        owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
        owncloud/ocis-konnectd@v0.3.2
        owncloud/ocis-migration@v0.2.0
        owncloud/ocis-ocs@v0.3.1
        owncloud/ocis-phoenix@v0.13.1-0.20200910090722-8e3ed0e966a5
        owncloud/ocis-pkg/v2@v2.4.1-0.20200902134813-1e87c6173ada
        owncloud/ocis-proxy@v0.7.1-0.20200907105449-201b9a652685
        owncloud/ocis-reva@v0.14.0
        owncloud/ocis-settings@v0.3.2-0.20200903035407-ad5de8264f91
        owncloud/ocis-store@v0.1.1
        owncloud/ocis-thumbnails@v0.3.0
        owncloud/ocis-webdav@v0.1.1
</pre>
</details>


Same.

**Comment by jnweiger** [comment]
## retested with desktop daily (20200908) client ownCloud version 2.7.0 (build 2058) on Ubuntu 18.04

different behaviour: a force sync or local file modification does not trigger the propagation of a server move or server delete with this client.

**Comment by pmaier1** [comment]
What you describe in https://github.com/owncloud/product/issues/127#issuecomment-692813312 is not a change via the WebUI as the title suggests but an external change directly on the storage, right?

While this should work I'd not consider this a blocker for 1.0.0.

What you describe in https://github.com/owncloud/product/issues/127#issuecomment-692822841 should work, though.

**Comment by jnweiger** [comment]
> What you describe in [#127 (comment)](https://github.com/owncloud/product/issues/127#issuecomment-692813312) is not a change via the WebUI as the title suggests but an external change directly on the storage, right?

Right, this extra test is not a requirement. I takeit as an indicator that the problem is closer to the client protocol than to the web UI.

**Comment by davitol** [comment]
Using https://168.119.56.223:9200/ instance I see the followong behavior:

Tested with Mac Version 2.7.0 (build 2098) and Windows desktop Client (2.7.0)


Log in with `Marie Curie` and upload a file in a folder => File gets synced in Desktop Local Folder


Log in with `Albert Einstein` and upload a file in a folder => File does NOT get synced in Desktop Local Folder

So IMHO it does not depend on the desktop client flavour but something related with the users

**Comment by butonic** [comment]
On a local setup following https://owncloud.github.io/ocis/eos/ etag propagation works and the sync client for einstein works fine.

**Comment by butonic** [comment]
to make eos propagate changes a folder needs the `sys.mtime.propagation` attribute set. check with:
```
EOS Console [root://mgm-master.testnet:1094] |/> attr ls "/eos/dockertest/reva/users/4/4c510ada-c86b-4815-8820-42cdf82c3d51"
sys.acl="u:2:rwxc"
sys.allow.oc.sync="1"
sys.eos.btime="1598367061.941900187"
sys.forced.atomic="1"
sys.forced.checksum="adler"
sys.mask="700"
sys.mtime.propagation="1"
sys.recycle="/eos/test/proc/recycle/"
```

**Comment by jnweiger** [comment]
The propagation always works fine with users marie, moss, richard. We see issues only with user einstein.
User einstein is special:
* Einstein's home
  * is created before the first login with `eos -r 0 0               mkdir -p /eos/dockertest/reva/users/4/4c510ada-c86b-4815-8820-42cdf82c3d51/`
  * has attrs
```
sys.acl="u:2:rwxc"
sys.eos.btime="1600420111.13831422"
sys.forced.checksum="adler"
sys.recycle="/eos/test/proc/recycle/"
```
* All other users' homes are created by the system.
  * They have additional attrs
```
sys.forced.atomic="1"
sys.mask="700"
sys.mtime.propagation="1"
```

It is a setup problem caused by preinstalling files into einstein's account at
https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh#L277

Sorry for the confusion!

**Comment by jnweiger** [comment]
Adding the above mentioned 4 attributes manually, fixes the issue.

**Comment by pmaier1** [comment]
> Manually adding the above mentioned four additional attributes on the home folder fixes the issue!

Is this documented somehow?
