### ISSUE TITLE
[OCIS] Sharing indicators status is not shown after reload or navigating

### ISSUE THREAD

**Issue by jnweiger** [owncloud/product#131]
Reproduce on ocis 1.0.0-beta8 with eos installed via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

firefox https://xxx.xxx.xxx.xxx:9200

*    log in as einstein,
*   create a folder `jw`
*    create a public link by clicking on the broken chain icon of `jw`
![image](https://user-images.githubusercontent.com/1108546/88213648-4af5cd80-cc59-11ea-88c5-421e74fd630a.png)
* the (overly prominent) `Shared with: ` indicator shows that the folder is shared.
* reload the page
![image](https://user-images.githubusercontent.com/1108546/88213870-9ad49480-cc59-11ea-806f-d41b139c736c.png)
* the indication that folder `jw` was shared disappears.

Expected behaviour: it stays.

**Comment by PVince81** [comment]
The behavior has changed slightly on latest ocis master (1bb8881f92b82f22ef47ce4b9be925164251817f):

1. create a folder "test"
1. click the anchor for direct link share (don't open the sidebar)
1. watch the row: no indicator appears!
1. reload the patch
1. watch the row: no indicator either
1. open the sidebar: indicator appears after the progress bar in the sidebar disappears

So two bugs:
- [ ] must update the indicator model/vue of the row after public link share was created
- [ ] must pre-load indicator data as soon as the page has loaded. Here is when we'd usually read the "oc-share-types" Webdav property for the row.

**Comment by PVince81** [comment]
of course!

OCIS doesn't return the "oc:share-types" property yet:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/277525/91457955-425e6b80-e885-11ea-81eb-603f0d47ae10.png">

**Comment by PVince81** [comment]
I have mixed feelings about reimplementing it the exact same way in OCIS. It requires getting all shares from the folder and aggregating the share types before returning them. As far as I remember it wasn't that performance in OC 10.
Unless there's a way to make this more performance in OCIS, we might want to consider other alternatives. But other alternatives might require other APIs, maybe more OCS Share calls for the folder.

**Comment by PVince81** [comment]
The OC 10 code is here: https://github.com/owncloud/core/blob/v10.5.0/apps/dav/lib/Connector/Sabre/SharesPlugin.php#L165

In OC 10 the shares are stored by node id aka file id. So we first fetch the directory entries for the Webdav response, and then for each node id, we call the internal share API to retrieve all shares for that node id (using a select ... where ... in ...), aggregate the share types, and inject them into the matching response entry.

In Reva I see we already have some way of filtering in place https://github.com/cs3org/reva/blob/master/pkg/share/manager/json/json.go#L348 so it might be just a matter of defining multiple filter entries with different resource ids when calling.

However, I'm unsure whether the webdav layer has access to the share provider/managers directly ?

**Comment by butonic** [comment]
The ocdav service currently lives in reva. It uses the cs3 api to fetch file Metadata and can also make requests to the share manager.

The storage provider itself also has grant managing rpc calls.

Ocdav can make calls to either of them... Or we try to fetch the grant information with the list container request...
