### ISSUE TITLE
login button has no visible feedback, when defunct

### ISSUE THREAD

**Issue by jnweiger** [owncloud/product#137]
Tested with owncloud/ocis:1.0.0-beta8

* log in at phoenix web ui 
* do some uploads
* wait 3 minutes for automatic logout
* kill the server hard, 
* restart a fresh server
* press the login button.
* nothing happens

![image](https://user-images.githubusercontent.com/1108546/87550117-fda0bb80-c6ae-11ea-979f-9223def779ac.png)

expected behaviour
* users always see a reaction when clicking a button. Here: Show a "tls: bad certificate" message on the gui.

**Comment by pmaier1** [comment]
> @pmaier1 Indicator that "something" is going on?

Yes, I think there should always be some indication (e.g., spinner). If that gets a timeout users can notice that something's wrong.

**Comment by kulmann** [comment]
:+1: for a spinner within the button.

Generally speaking I think it's a good approach for click actions on buttons, to disable the button and add a spinner on click, then re-activate the button and hide the spinner when the action/request is done. If a timeout happens it might make sense to hide the spinner and keep the button in a disabled state, but that is context-specific. A button that has been clicked should not be clickable again until clicking it is a valid action again. That might even be something for implementation in ODS. 🤔 @LukasHirt
