### ISSUE TITLE
Trashbin fails with unknown error when restoring

### ISSUE THREAD

**Issue by jnweiger** [owncloud/product#139]
On the web gui of owncloud/ocis:1.0.0-beta8 :

* upload a file
* delete the file
* upload the same file again
* go to trashbin, see the the copy of the file there
* restore from the trashbin, an error occurs:

![image](https://user-images.githubusercontent.com/1108546/87532296-3337ab80-c693-11ea-9a42-33f642fb1683.png)

Expected behaviour:
 * the error message should give the reason "cannot restore in the original location XXX, a file with the same name is already there."
 * and/or (even better) suggest to rename things to resolve that conflict, then restore.

**Comment by butonic** [comment]
fixed by https://github.com/cs3org/reva/pull/1103

**Comment by PVince81** [comment]
it's part of https://github.com/owncloud/ocis-reva/pull/447.

@individual-it @phil-davis any tests to enable on ocis-reva to validate this ?

**Comment by individual-it** [comment]
tests added in owncloud/core#37831  & owncloud/ocis#482
not many passing, need more investigation

**Comment by individual-it** [comment]
bug demonstration tests added in https://github.com/owncloud/ocis/pull/489

**Comment by individual-it** [comment]
phoenix tests added in owncloud/phoenix#3982 , taking off QA-team tag

**Comment by jnweiger** [comment]
## retested with
 * ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

<details>
<summary>Version details ocis-1.0.0-rc1</summary>

<pre>
OCIS_VERSION:         v1.0.0-rc1
ocis --version:       ocis version 199267c^M
git log:              commit 199267c13e916aa8de027a81dbf6733af820369f (HEAD, tag: refs/tags/v1.0.0-rc1)
eos --version:        EOS 4.6.5 (2019)^M
xrootd -v:            v4.11.0^M
bin/ocis contains:
        owncloud/ocis-accounts@v0.4.2-0.20200901074457-6a27781a2741
        owncloud/ocis-glauth@v0.5.1-0.20200731165959-1081de7c60f1
        owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
        owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
        owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
        owncloud/ocis-konnectd@v0.3.2
        owncloud/ocis-migration@v0.2.0
        owncloud/ocis-ocs@v0.3.1
        owncloud/ocis-phoenix@v0.13.0
        owncloud/ocis-pkg/v2@v2.4.1-0.20200828095914-d3b859484b2b
        owncloud/ocis-proxy@v0.7.1-0.20200904132806-fcceec602fcb
        owncloud/ocis-reva@v0.13.0
        owncloud/ocis-settings@v0.3.2-0.20200902094647-35dc3aeaba78
        owncloud/ocis-store@v0.1.1
        owncloud/ocis-thumbnails@v0.3.0
        owncloud/ocis-webdav@v0.1.1

</pre>
</details>

Restore works fine in RC1. No error messages when the target name is free. Appropriate errors when the target file or directory exists. Nothing is overwritten.
