### ISSUE TITLE
Configure OCIS to use another IDP

### ISSUE THREAD

**Issue by labkode** [owncloud/product#143]
Pointing at an external IDP service via environment variables (PHOENIX_OIDC_AUTHORITY, PHOENIX_OIDC_METADATA_URL, PHOENIX_WEB_CONFIG_SERVER & REVA_OIDC_ISSUER) does not work as expected:

```
2020-07-30T17:37:40Z DBG adding route route={"ApacheVHost":false,"Backend":"http://localhost:9130","Endpoint":"/.well-known/","Type":""} service=proxy
# Then, when hitting the EP:
2020-07-30T17:48:46Z DBG director found path=/.well-known/openid-configuration policy=reva prefix=/.well-known/ routeType=prefix service=proxy

```
No internal svc is running on that port nor the requests are proxied, so we get 502 from nginx.

**Comment by micbar** [comment]
Sure, this should work. If not, consider it as a bug.

@IljaN @felixboehm @GeraldLeikam are working on that.

**Comment by labkode** [comment]
Label it as bug

**Comment by labkode** [comment]
Try with flags

**Comment by micbar** [comment]
@labkode see https://owncloud.github.io/ocis/deployment/ocis_external_konnectd/

It works in a demo deployment scenario

**Comment by labkode** [comment]
From Jörn Dreyer to Everyone: (2:09 PM)
 https://owncloud.github.io/ocis/deployment/ocis_external_konnectd/

**Comment by labkode** [comment]
We need a config option in OCIS to proxy requests to the well-known service to our Idp. @butonic

**Comment by butonic** [comment]
- [ ] Double check if we can rewrite the `.well-known/openid-configuration` when forwarding it to an external idp

**Comment by michaelstingl** [comment]
@labkode @SamuAlfageme @diocas Did you test latest desktop and mobile versions and can you confirm they work? In case of problems, please report in new issues.

**Comment by SamuAlfageme** [comment]
@michaelstingl we're waiting for a change (the `-Dkeycloak.frontendUrl=` flag) to be rolled into our central keycloak to test the E2E auth8n workflow again with the clients. 

But so far, the behavior from the ocis-proxy policy was correct and the clients get answered with the `openid-configuration` without redirections.
