### ISSUE TITLE
Ensure security of pre-signed URLs

### ISSUE THREAD

**Issue by PVince81** [owncloud/product#150]
Make sure we only limit the signature to GET requests and only the specific call if possible to avoid abuse.

@butonic

**Comment by C0rby** [comment]
Is this only relevant for oCIS or also for oC10?

**Comment by PVince81** [comment]
this ticket was with OCIS in mind as we noticed that the current code might not be sufficient
this topic might be good to also check OC 10...

**Comment by C0rby** [comment]
After skimming through the code I saw that both OCIS and OC10 allow all HTTP methods.
If we want to only allow specific methods or endpoints we would need to implement something.

**Comment by PVince81** [comment]
please link to the PRs
