### ISSUE TITLE
tests for TUS protocol

### ISSUE THREAD

**Issue by individual-it** [owncloud/product#153]
currently there are no tests for the TUS protocol, but we rely heavily on it and there have been already issues with it, so we need some research and find out how best to test the TUS implementation

**Comment by dpakach** [comment]
We can start this by looking into the official docs for TUS protocol
docs: https://tus.io/protocols/resumable-upload.html

Clients for Tus
golang: https://github.com/tus/tusd
PHP: https://github.com/ankitpokhrel/tus-php

**Comment by individual-it** [comment]
- [ ] check if OPTIONS requests gives all the needed and correct information https://tus.io/protocols/resumable-upload.html#options
- [ ] creation with upload https://tus.io/protocols/resumable-upload.html#creation-with-upload (does the lib support that? If not we maybe can implement it)
- [ ] chunking but send chunks in reverse/random order (currently I cannot see a way to achieve that with the lib we are using - maybe we can make `Client::sendPatchRequest` public)
- [ ] overwrite files
- [ ]  upload to a non-existing folder (should be possible to get a good Exception after https://github.com/ankitpokhrel/tus-php/pull/324)
- [ ] rewrite chunks/send same chunk again
- [ ] different size of chunks

**Comment by individual-it** [comment]
- [ ] check if OPTIONS requests gives all the needed and correct information https://tus.io/protocols/resumable-upload.html#options
- [ ] creation with upload https://tus.io/protocols/resumable-upload.html#creation-with-upload (does the lib support that? If not we maybe can implement it)
- [ ] chunking but send chunks in reverse/random order (currently I cannot see a way to achieve that with the lib we are using - maybe we can make `Client::sendPatchRequest` public)
- [ ] overwrite files
- [ ]  upload to a non-existing folder (should be possible to get a good Exception after https://github.com/ankitpokhrel/tus-php/pull/324)
- [ ] rewrite chunks/send same chunk again
- [ ] different size of chunks

**Comment by swoichha** [comment]
We have added enough tests for TUS protocol to upload resources for now. So, closing this issue.
