### ISSUE TITLE
shares & public links are lost when renaming a file

### ISSUE THREAD

**Issue by individual-it** [owncloud/product#154]
- start ocis
- login to phoenix
- upload a file
- create a public link
- share with an other user
- rename the file
- look for the share and the public link

with API:
- upload: `curl -k -u einstein:relativity -X PUT https://localhost:9200/remote.php/webdav/src.txt -d"123"`
- create public link: `curl -k -u einstein:relativity  'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares' --data-raw 'shareType=3&path=%2Fsrc.txt&permissions=1'`
- check link: `curl -k -u einstein:relativity 'https://ocis-server:9200/ocs/v1.php/apps/files_sharing/api/v1/shares'  | xmllint --format -`
- rename: `url -k -u einstein:relativity -X MOVE https://localhost:9200/remote.php/webdav/src.txt -H"Destination: https://localhost:9200/remote.php/webdav/dest.txt"`
- check link: `curl -k -u einstein:relativity 'https://ocis-server:9200/ocs/v1.php/apps/files_sharing/api/v1/shares'  | xmllint --format -`

**Comment by jasson99** [comment]
Re-opened because encountered this similar issue: https://github.com/owncloud/product/issues/295
