### ISSUE TITLE
File deletion using dav gives unique string in filename in the trashbin

### ISSUE THREAD

**Issue by dbergstrom8** [owncloud/product#178]
### Steps to reproduce
1. create a file for eg; 'file.txt'
2. Now delete the file using dav api
`curl -k -u einstein:relativity -X DELETE https://localhost:9200/remote.php/dav/files/einstein/file.txt -v`
3. Now browse to `Trash bin` page
![Screenshot from 2020-08-25 14-31-05](https://user-images.githubusercontent.com/34328907/91153197-a1827b80-e6df-11ea-8043-e5e28d1b8efe.png)

As, you can see in the above screenshot the filename consists of some unique string (maybe file id, idk)

### Expected behavior
Now let's repeat above steps but deleting file using `webdav` api
1. create a file for eg; `file.txt`
2. Delete the created file using `webdav` api
`curl -k -u einstein:relativity -X DELETE https://localhost:9200/remote.php/webdav/file.txt -v`
3. Now browse to `Trash bin` page
![Screenshot from 2020-08-25 14-35-16](https://user-images.githubusercontent.com/34328907/91153740-59b02400-e6e0-11ea-8a38-c495b00f9ad1.png)

**Comment by phil-davis** [comment]
The "unique string" is likely the UUID of user `einstein` (being displayed in error)

**Comment by HariBhandari07** [comment]
When file/folder deletion is done using webUI, `UUID` doesn't appear infront of the file name in trashbin (similar to expected behavior screenshot)

**Comment by grgprarup** [comment]
Fixed: The issue no longer exists, tested manually. So, I am closing this.
