### ISSUE TITLE
Deleting a file with filename containing & doesn't appear in trashbin webUI

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/product#183]
#### case1
1. Create a file that contains `&` in filename (for eg; `file&.txt`)
2. Now delete the created file
3. Now browse to trashbin. Here, trashbin is empty

#### case2
Stop the ocis server and delete all the clear ocis files (delete all reva and ocis files inside `var/tmp`)
Start the ocis server
1. Create two files: `file.txt` and `file&.txt`
2. Batch delete both of them
3. Browse to trashbin page
![Screenshot from 2020-08-26 16-19-40](https://user-images.githubusercontent.com/34328907/91293589-fb567480-e7b7-11ea-9dd6-bbb6a006ab0e.png)

Other various unusual behaviors are observed in trashbin when a file name consist  of `&`

**Comment by HariBhandari07** [comment]
This issue may also be related https://github.com/owncloud/ocis-reva/issues/111

**Comment by michaelstingl** [comment]
Fixed:

![CleanShot 2023-03-22 at 17 43 11](https://user-images.githubusercontent.com/214010/226976765-6b3c7b39-acfb-4c7f-91a8-54426544a0ec.png)
