### ISSUE TITLE
Deletion of a recursive folder from trashbin is not possible

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/product#188]
### Steps to reproduce
1. Create a folder `parent1/child1`
3. Browse to trashbin
4. Try to delete `parent1` from trashbin. It fails
5. Restore `parent1` from trashbin. It succeeds
![Screenshot from 2020-08-27 15-01-39](https://user-images.githubusercontent.com/34328907/91421943-420aa400-e876-11ea-82be-b5961962ca91.png)

**Comment by PVince81** [comment]
which ocis version ? we had some trashbin fixes merged recently on ocis master

**Comment by HariBhandari07** [comment]
> which ocis version ? we had some trashbin fixes merged recently on ocis master

@PVince81  latest master branch

**Comment by PrajwolAmatya** [comment]
Similar to the issue https://github.com/owncloud/ocis/issues/1077 and mentioned in the comment https://github.com/owncloud/ocis/issues/1077#issuecomment-816592459, the issue does not exist in current master. E2E test is covered in this PR https://github.com/owncloud/web/pull/10449. So, closing this issue.
