### ISSUE TITLE
[EOS] enable and run sharing tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/product#191]
sharing should (partly) work on EOS, so we should be able to enable those tests with EOS.
Special case with EOS:
- all shares need to be accepted
- shares are only accessible through the `/Shares` folder

**Comment by dpakach** [comment]
We can run the sharing tests with EOS currently. Even though it's not implemented on CI, Few tests pass but many fail. But we cannot completely rely on the results of the test run.
The main problem is the shares cannot be cleared properly after running the tests. 
https://github.com/owncloud/ocis-reva/issues/357#issuecomment-693188299

**Comment by individual-it** [comment]
done by https://github.com/owncloud/core/pull/37796
