### ISSUE TITLE
Review API test output in OCIS

### ISSUE THREAD

**Issue by phil-davis** [owncloud/product#192]
The core API acceptance tests are run in OCIS repos to check how well the OCIS APIs conform to oC10 behavior. The OCIS repos sometimes do not (yet) provide "reasonably close" responses to what is returned by oC10.

Some of the test code assumes that a "reasonable" response is received, and starts to parse that and check the detail. And the test code gets some PHP error/notice/exception...

For example,
`Notice: Undefined index: users in /srv/app/testrunner/tests/acceptance/features/bootstrap/ShareesContext.php line 152`
was fixed in PR https://github.com/owncloud/core/pull/37844

- check the drone output of the pipeline steps that run the core API acceptance tests
- look for fails that emit error/notice/exception messages, or where the failure message is not clear
- improve the core acceptance test code so that it does better checks and emits more useful messages

Check in all 3 of `cs3org/reva` `owncloud/ocis-reva` and `owncloud/ocis`

The objective is to make it easier for developers to understand the test failures and be able to more quickly find where the problem is likely to be.

**Comment by phil-davis** [comment]
While trying to enable a lot more API tests, I added and refactored a lot of error messages:
https://github.com/owncloud/core/pull/37868
https://github.com/owncloud/ocis-reva/issues/415

I didn't look at the "normal" test runs in OCIS CI - I did test PRs to run all the tests that are not currently run.

If you don't see any other "bad error messages" in a normal OCIS CI run, then close this issue.

**Comment by HariBhandari07** [comment]
As of now, there are no "bad error messages". So, closing this issue.
