### ISSUE TITLE
[GW] Non configurable storage backends

### ISSUE THREAD

**Issue by diocas** [owncloud/product#193]
On the gateway, the config is [enforcing](https://github.com/owncloud/ocis-reva/blob/f74320d85d09e245e1023ae38dd33774eaca978a/pkg/command/gateway.go#L129) a limited set of Storage backends.

For us, at CERN, this needs to be configurable. We have multiple EOS backends and we need to be able to mount them.

**Comment by butonic** [comment]
fixed by https://github.com/owncloud/ocis-reva/pull/461
