### ISSUE TITLE
[Phoenix] Inconsistent row height in files app (thumbnails)

### ISSUE THREAD

**Issue by kulmann** [owncloud/product#194]
### Steps to reproduce
1. Upload multiple pictures with different aspect ratios, at least one in a portrait and one in a landscape ratio
2. See how row heights are different depending on the thumbnail height, making the UI very noisy
### Expected behaviour
All rows should have the same height

### Actual behaviour
Row heights change, depending on the thumbnail aspect ratio. Thumbnails have a fixed width.

<img width="1419" alt="Screenshot 2020-08-21 at 11 47 59" src="https://user-images.githubusercontent.com/3532843/90877658-b9d35d00-e3a4-11ea-9439-ccfd261ba6cd.png">

This is very subjective, but I in my opinion it is absolutely required that row height is the same for all rows. I am open for other opinions, please explain yours if it's different.

Ideas for solving this:
a) Change thumbnails to a fixed height instead of fixed width and then align to the center horizontally. This has the risk that a very narrow, tall image will have a very small thumbnail size, making it somewhat useless. But it's still better than the current state.
b) Change thumbnails to a fixed aspect ratio, crop if necessary. As always, generic cropping of images might lead to funny looking results.

**Comment by PVince81** [comment]
A quickfix here that actually sets a height for the preview: https://github.com/owncloud/phoenix/pull/4073

Do we want to keep this ticket open ?

**Comment by PVince81** [comment]
PR was merged for the quick fix. I'll close this issue here.

For smart cropping, follow up in https://github.com/owncloud/product/issues/184
