### ISSUE TITLE
[Phoenix] IE11 support for public link uploads

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/product#20]
IE11 is deprecated for oCIS-Phoenix.

Would it be possible to support IE11 for public link uploads?
(maybe with less fancy, very basic fallback mode)

Why?
Organisations can't really control the browsers users outside their organisation use.

/cc @micbar

**Comment by micbar** [comment]
Next step. Product Roadmap

**Comment by DeepDiver1975** [comment]
@PVince81 as discussed some time ago - a dedicated micro frontend for public files could help here ... just saying

**Comment by michaelstingl** [comment]
Internet Explorer 11 has retired and is officially out of support
- https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/
