### ISSUE TITLE
ocis UI tests failing after account cache in ocis-proxy is removed

### ISSUE THREAD

**Issue by kulmann** [owncloud/product#219]
Web ui tests are failing on CI on this PR:
https://github.com/owncloud/ocis/pull/525

Example drone run with the failures:
https://cloud.drone.io/owncloud/ocis/1505/6/7

Timeline and things I noticed:
- at first the ocis PR was only pulling the new ocis-proxy version that removes the accounts cache from the account_uuid middleware, i.e. this PR from ocis-proxy: https://github.com/owncloud/ocis-proxy/pull/100
- in this early state, CI was already failing
- the first failing test in CI is tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature:95
- when running that test standalone, it succeeds. If you run the full test suite CI fails.
- after some more digging, I found out that when a request to ocis-accounts is coming through grpc (which is the case for ocis-ocs), the handler was not provided with a client for the ocis-settings roleService. Because of that, setting the default user role on newly created accounts didn't work. I fixed that with this PR https://github.com/owncloud/ocis-accounts/pull/114 and pulled it into this ocis PR as well.
- CI is still failing with the exact same behaviour: the login times out in the same test scenario as stated above, resulting in `70 scenarios (36 failed, 34 passed)`. Always.
- one assumption is that it has to do with OCS, failing to recreate `user1` after deleting it. If that's true, the account cache in ocis-proxy would have hidden that, because, well, the account was cached in ocis-proxy. The cache doesn't exist anymore.
- I can't see anything wrong with the test before the failing one (i.e. tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature:65). Thought it might be leaving the server in an invalid state for that user1 but can't find anything wrong.

@individual-it @phil-davis @dpakach

**Comment by phil-davis** [comment]
The test was skipped by Phoenix PR https://github.com/owncloud/phoenix/pull/4051 and OCIS PR https://github.com/owncloud/ocis/pull/540

Now the underlying cause needs to be found, fixed, and the test scenario enabled again.

**Comment by kulmann** [comment]
It looks like the failure is appearing in different tests now. Some drone runs that failed with identical symptoms:
- https://cloud.drone.io/owncloud/ocis/1571/6/7
- https://cloud.drone.io/owncloud/ocis/1572/6/7
- https://cloud.drone.io/owncloud/ocis/1594/13/7
- https://cloud.drone.io/owncloud/ocis/1595/13/7
- https://cloud.drone.io/owncloud/ocis/1613/13/7

**Comment by phil-davis** [comment]
I added this to the "OCIS Server QA/CI Automation" project so that it keeps being noticed by QA. Next step is to get the "no duplicate accounts" code merged... Then we can see if there is more to be done.

**Comment by individual-it** [comment]
how to reproduce it manually:

1. start ocis
2. create a user called `user1`   `curl -k -XPOST https://localhost:9200/ocs/v2.php/cloud/users?format=json -uadmin:admin -d"username=user1&email=user1%40example.org&userid=user1&password=1234`
3. login as `user1` to phoenix
4. start an action with a lot of requests that will take a while e.g. delete all files or upload a lot of files
5. while the action is in process delete the user: `curl -k -XDELETE https://localhost:9200/ocs/v2.php/cloud/users/user1?format=json -uadmin:admin;`
6. check content of `/var/tmp/ocis-accounts/accounts/` => the new account file (with uuid as file-name) was created
7. create user `user1` again and try to login

**Comment by kulmann** [comment]
aha, so the user gets auto-provisioned again from the IDP claims. which can only work if in the proxy:
1) the oidc middleware successfully finds the user claims (which come fromaccounts, through glauth!!!)
2) the user gets deleted (your step 5)
3) the account_uuid middleware doesn't find the user and auto-provisions it. because the claims from oidc are in the context.
