### ISSUE TITLE
adjust creating skeleton folder and user data deletion for API tests when using OCIS-storage

### ISSUE THREAD

**Issue by individual-it** [owncloud/product#223]
when using OCIS storage and creating a user, we cannot just dump files into the folder to emulate the skeleton folder as we do with the OC storage but we need to upload the items via WebDav.

to delete data of the user after deleting the user our current delete strategy does not work, (https://github.com/owncloud/core/blob/828f07802fa3b977fcdbf315f9671d5442288886/tests/TestHelpers/OcisHelper.php#L68) we have to use a delete command

To accomplish both that we have currently to set 
```
'TEST_OCIS':'true'
'OCIS_REVA_DATA_ROOT':''
'DELETE_USER_DATA_CMD':'rm -rf /srv/app/tmp/ocis/root/nodes/root/*'
```
see https://github.com/owncloud/ocis-reva/pull/466/files#diff-74dc60589e0610c07e491b31f8693b2bR112-R129

it would be better to simplify that, maybe have an other setting like `REVA_STORAGE_OC_DRIVER` and according to that `deleteRevaUserData` will delete the correct folder and choose to upload the skeleton via WebDAV

**Comment by phil-davis** [comment]
Needs some thought/discussion about the flow/configuration of env variables etc.

**Comment by individual-it** [comment]
Alternative approach: leave the deletion as it is and make a new switch for the skeleton provisioning strategy: https://github.com/owncloud/core/pull/38005

**Comment by phil-davis** [comment]
When we next bump the core commit id for tests in OCIS, we should define `OCIS_SKELETON_STRATEGY` to be "copy" (if that works), otherwise define it to be "upload".

**Comment by individual-it** [comment]
@phil-davis the change of env variables is done in https://github.com/owncloud/ocis/pull/691
