### ISSUE TITLE
[QA] Phoenix thumbnails are misplaced

### ISSUE THREAD

**Issue by jesmrec** [owncloud/product#232]
I performed the following steps

1. Create a folder
2. Using iOS client, upload a bunch of images from albums
3. Open folder in Phoenix

Current:

Thumbnails are misplaced 

![Screenshot 2020-09-15 at 12 50 08](https://user-images.githubusercontent.com/14894746/93202013-4843c000-f752-11ea-93b1-5ca24e32ae4f.png)

Firefox 80.0.1
Chrome 85.0.4183.102

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/phoenix/pull/4073

**Comment by pmaier1** [comment]
Awesome, yes, thank you!
