### ISSUE TITLE
phoenix logout happens while working

### ISSUE THREAD

**Issue by jnweiger** [owncloud/product#235]
Reproduce on ocis 1.0.0-beta8, 1.0.0-rc1 with eos installed via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

* log in user einstein with firefox
* slowly do many actions: upload files, create folders, delete files, remove folders, so that time passes.
* while working, suddenly a logout occurs:
![image](https://user-images.githubusercontent.com/1108546/88314080-b51f7880-cd14-11ea-80f0-74efc647d4c6.png)
* I can continue type the folder name, but 'Create' does nothing.
* 'Cancel' makes the requester disappear, leaving me on a normal login screen
![image](https://user-images.githubusercontent.com/1108546/88314276-f3b53300-cd14-11ea-9c17-18869b185f7e.png)

Expected behaviour:
* No. Do not interrupt users like that.

**Comment by butonic** [comment]
hm locally the silent refresh works and keeps updating the access token ... so, might be a config issue ...

**Comment by butonic** [comment]
definitely a config issue. on localhost I see token refresh requests, which do not happen on ocis.owncloud.works

**Comment by butonic** [comment]
I take it back ... it just fetched a new access token on ocis.owncloud.works

**Comment by jnweiger** [comment]
yes, ocis.owncloud.works and my setup script both have the same config issue, if it is a config issue. 10min logout everywhere.

**Comment by jnweiger** [comment]
## Retested with
 * ocis master from 5h ago
 * firefox
 * chromium

<details>
<summary> ocis master version details</summary>

<pre>
OCIS_VERSION:         master
ocis --version:       ocis version 7b8e9bc
git log:              commit 7b8e9bc2981c0fd9917bc576a291ab5231c02685 (HEAD -> refs/heads/master, refs/remotes/origin/master, refs/remotes/origin/HEAD)
eos --version:        EOS 4.6.5 (2019)
xrootd -v:            v4.11.0
bin/ocis contains:
	owncloud/ocis-accounts@v0.4.2-0.20200911161616-e55b8ae2f440
	owncloud/ocis-glauth@v0.5.1-0.20200909064150-0735ec933777
	owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
	owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
	owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
	owncloud/ocis-konnectd@v0.3.2
	owncloud/ocis-migration@v0.2.0
	owncloud/ocis-ocs@v0.3.2-0.20200916110615-7ca52baa61c4
	owncloud/ocis-phoenix@v0.13.1-0.20200910090722-8e3ed0e966a5
	owncloud/ocis-pkg/v2@v2.4.1-0.20200902134813-1e87c6173ada
	owncloud/ocis-proxy@v0.7.1-0.20200907105449-201b9a652685
	owncloud/ocis-reva@v0.14.0
	owncloud/ocis-settings@v0.3.2-0.20200903035407-ad5de8264f91
	owncloud/ocis-store@v0.1.1
	owncloud/ocis-thumbnails@v0.3.0
	owncloud/ocis-webdav@v0.1.1
</pre></details>

Rumors about increased 1h timeout instead of 10min **cannot** be confirmed with this deployment.
Both tested browsers log out exaxtly after 10 min.
