### ISSUE TITLE
Review causes of expected-failures

### ISSUE THREAD

**Issue by phil-davis** [owncloud/product#245]
Review the lists of expected failures of API tests in:
https://github.com/owncloud/ocis/blob/master/ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt
https://github.com/owncloud/ocis/blob/master/ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt

and add or update the comments with links to the related issues.

**Comment by dpakach** [comment]
Done in https://github.com/owncloud/ocis/pull/679
