### ISSUE TITLE
[OCIS] share permissions not enforced

### ISSUE THREAD

**Issue by dpakach** [owncloud/product#270]
Currently in OCIS setting share permissions doens't enforces it.

for eg. 
1. create a share with `Viewer` role
2. login as sharee and accept the share.
3. Try to create a new file/folder or share the received share to another users.

- Expected - it should not be possible
- Actual - it is possible

**Comment by pmaier1** [comment]
This has been fixed meanwhile, right? Please close if that is the case.

**Comment by saw-jan** [comment]
A viewer cannot upload or create file/folder inside the shared folder.
![share-viewer-create-upload](https://user-images.githubusercontent.com/52366632/161741639-6b1f72eb-5c54-434d-a678-9fa813510f86.png)

But resharing is disabled in oCIS so cannot reshare to another user.
![share-viewer-reshare](https://user-images.githubusercontent.com/52366632/161741658-386e301b-da2b-411e-b82d-0bf01fc0ce51.png)

I am closing this.
