### ISSUE TITLE
[OCIS][OC Storage] etags are not updated consistently on file operations

### ISSUE THREAD

**Issue by dpakach** [owncloud/product#280]
The etags are updated inconsistently on some file operations. The etags are updated sometimes but are not updated other times.

As a result these tests fail intermittentely

- Deleting a folder on parents
apiWebdavEtagPropagation1/deleteFileFolder.feature

- Deleting a file in public shared folder on parents
apiWebdavEtagPropagation1/moveFileFolder.feature:171

- Deleting a folder in public shared folder on parents
apiWebdavEtagPropagation1/moveFileFolder.feature:240

- moving a folder into a subfolder on parents
apiWebdavEtagPropagation1/moveFileFolder.feature:97

- copying a file into a folder should change etags of parents
apiWebdavEtagPropagation2/copyFileFolder.feature:24
apiWebdavEtagPropagation2/copyFileFolder.feature:25
apiWebdavEtagPropagation2/copyFileFolder.feature:45
apiWebdavEtagPropagation2/copyFileFolder.feature:46
apiWebdavEtagPropagation2/copyFileFolder.feature:67
apiWebdavEtagPropagation2/copyFileFolder.feature:68
apiWebdavEtagPropagation2/copyFileFolder.feature:93
apiWebdavEtagPropagation2/copyFileFolder.feature:94
apiWebdavEtagPropagation2/copyFileFolder.feature:120
apiWebdavEtagPropagation2/copyFileFolder.feature:121

- creating a folder inside a folder should change etag of parent
apiWebdavEtagPropagation2/createFolder.feature:22
apiWebdavEtagPropagation2/createFolder.feature:23
apiWebdavEtagPropagation2/createFolder.feature:92

- restoring a version should change etags on parents
apiWebdavEtagPropagation2/restoreVersion.feature:10

- uploading a file inside a folder changes the etags of the parents
apiWebdavEtagPropagation2/upload.feature:139
apiWebdavEtagPropagation2/upload.feature:11

**Comment by kiranparajuli589** [comment]
closing in behalf of https://github.com/owncloud/ocis/issues/4251
