### ISSUE TITLE
User Managment Flow 

### ISSUE THREAD

**Issue by CarolinaCst** [owncloud/product#298]
### Scope: ownCloud Web

Objective: In order to enhance the actual User Management flow two methods have been developed: 
A)Overlay or full page
B)Sidebar  

Actual Landing Page:
https://ocis.owncloud.works

### Steps to reproduce

1. Home page is shown
2. Click on "Application Switcher"  and then "Accounts"
3. Accounts is displayed 

### A)Overlay 

* Multiple Users
Objective: Change "Role" using multiple selection

1. Select the users. The whole row will be highlighted.
2. On the top of the site a new banner with different options like "Role" will appear. Click on "Role".
3. A layout appears with the users names and the options to choose.

![image](https://user-images.githubusercontent.com/60343863/100339117-bc63d500-2fd9-11eb-9a94-57d137a5faf5.png)

4. Select the desired option and save it. 
5. The changes are save and shown on the site.
6. Link to the GIF: https://cloud.owncloud.com/index.php/s/FW0pDQ5uSFNkKBi

* Single User
Objective: Change "Role" of a user

1. Select the user. The whole row will be highlighted.
2. On the top of the site a new banner with different options like "Role" will appear. Click on it.
3. A layout appears with the user’s name and the options to choose. 

![image](https://user-images.githubusercontent.com/60343863/100341260-9ee43a80-2fdc-11eb-845f-58c0789ab762.png)

4. Select the desired option and save it. 
5. The changes are save and shown on the site.
6. Link to the GIF: https://cloud.owncloud.com/index.php/s/xbSzujz4VFUxA3T

### B)Sidebar

*Multiple Users

https://cloud.owncloud.com/index.php/s/f80uKAjvMutrmnt

*Single User
Objective: Change "Role" of a user

1. Select the user and click on the More vert icon, three dots.
![image](https://user-images.githubusercontent.com/60343863/100344143-a7d70b00-2fe0-11eb-8991-93169d9482af.png)

2. A sidebar appears with the users Profile appears on the right. Click in "Role"
![image](https://user-images.githubusercontent.com/60343863/100344362-fab0c280-2fe0-11eb-916a-a4a1fdbd86fc.png)

3. The actual "Role" will be display. Click again on it to choose the other options.
4. Select the desired option and save it.
5. The changes are save and shown on the site.
6. Link to GIF: https://cloud.owncloud.com/index.php/s/TNGueskMrDe1kOj

**Comment by wkloucek** [comment]
@tbsbdr please close if no longer relevant

**Comment by tbsbdr** [comment]
no longer relevant as we changed the mainlayout with the new design. And: the mentioned GIF assets are unfortunately missing.
