### ISSUE TITLE
ownCloud Web Delete Button change color

### ISSUE THREAD

**Issue by CarolinaCst** [owncloud/product#299]
Scope: ownCloud Web

Actual Landing Page:
https://ocis.owncloud.works/#/accounts

1. Delete Button

![image](https://user-images.githubusercontent.com/60343863/100349596-fe484780-2fe8-11eb-821e-d90bbdada28f.png)

2. Confirmation 
![image](https://user-images.githubusercontent.com/60343863/100349576-f7213980-2fe8-11eb-980a-f0126a70f8f5.png)

**Comment by wkloucek** [comment]
@tbsbdr please close if no longer relevant

**Comment by tbsbdr** [comment]
![image](https://user-images.githubusercontent.com/26610733/143823717-460e8ac1-cd10-4333-b441-dabea26cd872.png)
closing as color has been changed.
