### ISSUE TITLE
[Phoenix] own page for search results

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/product#32]
# User stories
- As a user, I want to be able to return back to the search results after navigating to some folder in case that the folder is not the one I was looking for
- As a user, I want to share the URL with all parameters with others to show them the same search query as I am seeing.

**Comment by michaelstingl** [comment]
Done ✅ 
- https://ocis.ocis-web.latest.owncloud.works/index.html#/files/search/list?term=cracker&provider=files.sdk&tiles-size=1&items-per-page=100&view-mode=resource-table&sort-by=name&sort-dir=asc
 (`einstein:relativity`)
