### ISSUE TITLE
add Example: Prometheus and Jager with oCIS

### ISSUE THREAD

**Issue by felixboehm** [owncloud/product#35]
- [ ] Status Prometheus ? @micbar 
- [ ] build a compose example
- [ ] add compose snippet for jaeger

---
by setting REVA_TRACING_ENABLED=true env, reva services should start sending traces to jaeger's default address
I do it by running the all-in-one jaeger image:

```
docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 14250:14250 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.17
```

**Comment by micbar** [comment]
Prometheus and Grafana https://github.com/owncloud-docker/compose-playground/pull/21

**Comment by wkloucek** [comment]
Monitoring and tracing story is now there for admins and developers. Migration of our testing oCIS deployments is still ongoing.
https://owncloud.github.io/ocis/development/tracing/
https://owncloud.github.io/ocis/deployment/monitoring-tracing/
https://github.com/owncloud-devops/monitoring-tracing-server
https://github.com/owncloud-devops/monitoring-tracing-client
