### ISSUE TITLE
Quick actions

### ISSUE THREAD

**Issue by pmaier1** [owncloud/product#37]
- Ref https://github.com/owncloud/phoenix/issues/1112
- Ref https://github.com/owncloud/phoenix/issues/2252

## User stories
- As a user I want to access frequently used functionality with as little interactions as possible directly from the resource listing
- Frequently used functionality is (TBD)

## Product doc
- PR INC

**Comment by LukasHirt** [comment]
Already implemented. Example quick actions - https://github.com/owncloud/web/blob/master/apps/files/src/quickActions.js
