### ISSUE TITLE
Gracefully handle permanet redirects in all clients

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/product#38]
# Desktop
A 301/308 code currently causes the desktop client silently update the server location.
This should most probably require a user interaction to accept the change.
Related: https://github.com/owncloud/client/commit/09173fb727ca271643657cb95de30844ff81a689

# Mobile
As a 301 is not handled correctly, the authentications against the redirect works but as POSTs on a 301 fail the clients get stuck in an undefined way.
No errors or warnings are displayed to the user.

308 not tested yet

**Comment by TheOneRing** [comment]
While ios did not display a proper dialog at first it suggested the update when I went to the settings.

**Comment by michaelstingl** [comment]
> it suggested the update when I went to the settings.

user flow will need some refinement…

**Comment by michaelstingl** [comment]
@TheOneRing what does the desktop UI show after it "learned" the redirect? Old URL or new URL?

**Comment by TheOneRing** [comment]
It completely replaces the old url without any user notice.
