### ISSUE TITLE
[iOS] Upload Improvements

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/product#51]
[[`IOS-14`]](https://jira.owncloud.com/browse/IOS-14)

### TUS

- Planned for 11.4 (Preview)
- Issue: https://github.com/owncloud/ios-app/issues/696
- Issue: https://github.com/owncloud/ios-sdk/issues/65

**Comment by michaelstingl** [comment]
TUS available as tech preview in 11.4

**Comment by Mich21050** [comment]
Does the current owncloud IOS app support chunked uploads?

**Comment by michaelstingl** [comment]
> Does the current owncloud IOS app support chunked uploads?

No chunked uploads with ownCloud 10 server, but resumable upload protocol ([`TUS`](https://tus.io)) with oCIS backend.
