### ISSUE TITLE
Configurable public shares file

### ISSUE THREAD

**Issue by PVince81** [owncloud/product#59]
Currently it's stored in "/var/tmp/.publicshare" hard-coded.

This should default to the reva folder instead, maybe "/var/tmp/reva/publicshares.json" and be configurable.

## Tasks
- [ ] Create storage target folder beforehand
- [ ] Use a config option for the storage location

## Estimation
Complexity: S
Effort: S

**Comment by C0rby** [comment]
What was meant by `Create storage target folder beforehand`?

**Comment by PVince81** [comment]
I think it is the target folder in which the config file is contained.
So if that folder is not there, writing a file there would fail.

**Comment by C0rby** [comment]
I see, okay added that.

**Comment by PVince81** [comment]
Fix is here: https://github.com/cs3org/reva/pull/820
