### ISSUE TITLE
Missing Content-Length response header

### ISSUE THREAD

**Issue by abelgardep** [owncloud/product#70]
File request does not always retrieve `Content-Length` in Response Header.

- oC10: Always retrieved
- ocis: Retrieved on plain/text but not retrieved on pdf or image requests

Reproduced with Server: ocis-latest.owncloud.com einstein:relativity

## Tasks
- [ ] Debug Reva, fix it

## Estimation
M / M (escalate if it grows bigger)

**Comment by C0rby** [comment]
Implemented in cs3org/reva but not yet merged into ocis-reva.
