### ISSUE TITLE
cli to manage users

### ISSUE THREAD

**Issue by butonic** [owncloud/product#88]
ocis-accounts currently hasn no cli to
- [ ] list users
- [ ] add users
- [ ] update users
- [ ] remove users
- [ ] reindex a user in case someone edited the json file on disk

take care to find a non colliding uidnumber and a suitable gidnumber. discussion on how to do that is in https://github.com/owncloud/ocis-accounts/issues/47

**Comment by micbar** [comment]
Closed by https://github.com/owncloud/ocis-accounts/pull/69
