### ISSUE TITLE
[Desktop] Placeholder improvements

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/product#9]
There are several issues with the current implementation.
This lies in the nature of the current implementation.
Placeholder files hold no data, only the file name provides data.
If we would write the original file path and hash to the file, we could detect a move when encountering placeholder in a new location....

- https://github.com/owncloud/client/issues/7557
- https://github.com/owncloud/client/issues/7327
- https://github.com/owncloud/client/issues/7677 ...

**Comment by michaelstingl** [comment]
Placeholder improvements not planned. Efforts should go into native VFS implementations.
